sonar.projectKey=joaoelian204_Portal-Ciudadano-Manta-web
sonar.organization=joaoelian204

# Esto le dice que mande los datos a la nube
sonar.host.url=https://sonarcloud.io

# Esto analiza todo el código de la carpeta actual
sonar.sources=.

# Esto evita que analice librerías externas (importante para que no tarde años)
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/test/**
